### DISCUSSION TITLE
Docker conductor

### DISCUSSION THREAD

**Discussion by javiercanillas** [Netflix/conductor#2591] [Ideas]
I have been struggling to allow the conductor docker image to be able to call a service hosted on my local machine. I found a way to achieve this by changing a little part of the docker image.

This is useful if you are working with a HTTP task and the endpoint is exposed on the host of the docker image (imagine working locally on a feature where the conductor is hosted on docker and you are developing the endpoint to be called).

So I modified `docker/docker-compose.yaml` and added a new entry below `conductor-server` as follows:
```yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

By doing so, the whole `conductor-server` entry ended like the following:
```yaml
conductor-server:
    environment:
      - CONFIG_PROP=config-local.properties
    image: conductor:server
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    networks:
      - internal
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl","-I" ,"-XGET", "http://localhost:8080/health"]
      interval: 60s
      timeout: 30s
      retries: 12
    links:
      - elasticsearch:es
    depends_on:
      elasticsearch:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

So when I rebuild the image, I can setup an HTTP task like the following:
```json
{
  "name": "my-http-call"
  "taskReferenceName": "my-http-call",
  "description": "Fire custom http call",
  "inputParameters": {
    "http_request": {
      "asyncComplete": "false",
      "connectionTimeOut": "100",
      "contentType": "application/json",
      "body": {
        "workflowInstanceId": "${workflow.workflowId}",
      },
      "method": "POST",
      "uri": "http://host.docker.internal:8081/myCall",
      "readTimeOut": 1000,
      "accept": "application/json"
    }
  }
  "type": "HTTP",
  "decisionCases": {},
  "defaultCase": [],
  "forkTasks": [],
  "startDelay": 0,
  "joinOn": [],
  "optional": false,
  "defaultExclusiveJoinTask": [],
  "asyncComplete": false,
  "loopOver": [],
  "retryCount": 3
}
```

Do you think this configuration should be the default?
