### DISCUSSION TITLE
Large time gaps between system tasks

### DISCUSSION THREAD

**Discussion by arketec** [Netflix/conductor#2898] [Q&A] [answered]
Hello,

We have been having issues with 30 second gaps between system tasks like HTTP or SWITCH tasks. Here is a screenshot of a sample:
![conductor_gaps](https://user-images.githubusercontent.com/1336974/161814399-923a35e4-4915-4316-9a8e-17045b749f75.PNG)

We have scaled up conductor recently, and are now running it with a hosted elasticsearch cloud service and we created a 3 node cluster for dynomite in HA mode on 3 VMs that it uses.

We were seeing this issue before with Simple tasks because we had a bug where the workers were polling 100 times a second which was causing Conductor Server to slow down a lot. We fixed that, but now we are seeing these time gaps in the system tasks, which should not be affected by the polling interval we changed in our workers.

Any idea why these system tasks would be taking so long to start?

edit: 
here is the config for conductor server
```
# Servers.
conductor.grpc-server.enabled=false

# Database persistence type.
conductor.db.type=dynomite

# Dynomite Cluster details.
# format is host:port:rack separated by semicolon
conductor.redis.hosts=dyno1:8102:us-east-1b;dyno2:8102:us-east-1b;dyno3:8102:us-east-1b
conductor.redis.availabilityZone=us-east-1b

# Dynomite cluster name
conductor.redis.clusterName=dyno1

# Namespace for the keys stored in Dynomite/Redis
conductor.redis.workflowNamespacePrefix=conductor

# Namespace prefix for the dyno queues
conductor.redis.queueNamespacePrefix=conductor_queues

# No. of threads allocated to dyno-queues (optional)
queues.dynomite.threads=100

# By default with dynomite, we want the repairservice enabled
conductor.app.workflowRepairServiceEnabled=true

# Non-quorum port used to connect to local redis.  Used by dyno-queues.
# When using redis directly, set this to the same port as redis server
# For Dynomite, this is 22122 by default or the local redis-server port used by Dynomite.
conductor.redis.queuesNonQuorumPort=22122

# Elastic search instance indexing is enabled.
conductor.indexing.enabled=true

workflow.elasticsearch.instanceType=external
# Transport address to elasticsearch
conductor.elasticsearch.url=https://es:9243

# Name of the elasticsearch cluster
conductor.elasticsearch.indexName=conductor
conductor.elasticsearch.username=REMOVED
conductor.elasticsearch.password=REMOVED

#workflow.elasticsearch.version=6
#workflow.elasticsearch.cluster.health.color=green
#workflow.elasticsearch.async.dao.worker.queue.size=500
#workflow.elasticsearch.async.dao.max.pool.size=24
#conductor.event-queues.amqp.queueType=classic
#conductor.event-queues.amqp.sequentialMsgProcessing=true

# Additional modules for metrics collection exposed via logger (optional)
conductor.metrics-logger.enabled=true
# conductor.metrics-logger.reportPeriodSeconds=15

# Additional modules for metrics collection exposed to Prometheus (optional)
 #conductor.metrics-prometheus.enabled=true
 #management.endpoints.web.exposure.include=prometheus

# To enable Workflow/Task Summary Input/Output JSON Serialization, use the following:
# conductor.app.summary-input-output-json-serialization.enabled=true

# Load sample kitchen sink workflow
loadSample=true

```

this is the dynomite cluster config:
```
dyn_o_mite:
  datacenter: dc1
  rack: rack1
  dyn_listen: 0.0.0.0:8101
  dyn_seeds:
    - host2:8101::rack1:dc1:1431655765
    - host3:8101:rack1:dc1:2863311530
  listen: 0.0.0.0:8102
  servers:
    - 0.0.0.0:22122:1
  tokens: "0"
  secure_server_option: datacenter
  pem_key_file: conf/dynomite.pem
  data_store: 0
  stats_listen: 0.0.0.0:22221
  datastore_connections: 3
  local_peer_connections: 3
  remote_peer_connections: 3
```
```
dyn_o_mite:
  datacenter: dc1
  rack: rack1
  dyn_listen: 0.0.0.0:8101
  dyn_seeds:
    - host1:8101::rack1:dc1:0
    - host3:8101:rack1:dc1:2863311530
  listen: 0.0.0.0:8102
  servers:
    - 0.0.0.0:22122:1
  tokens: "1431655765"
  secure_server_option: datacenter
  pem_key_file: conf/dynomite.pem
  data_store: 0
  stats_listen: 0.0.0.0:22221
  datastore_connections: 3
  local_peer_connections: 3
  remote_peer_connections: 3
```
```
dyn_o_mite:
  datacenter: dc1
  rack: rack1
  dyn_listen: 0.0.0.0:8101
  dyn_seeds:
    - host1:8101::rack1:dc1:0
    - host2:8101:rack1:dc1:1431655765
  listen: 0.0.0.0:8102
  servers:
    - 0.0.0.0:22122:1
  tokens: "2863311530"
  secure_server_option: datacenter
  pem_key_file: conf/dynomite.pem
  data_store: 0
  stats_listen: 0.0.0.0:22221
  datastore_connections: 3
  local_peer_connections: 3
  remote_peer_connections: 3
```
