### ISSUE TITLE
RuntimeException when starting custom conductor-server container, connections refused

### ISSUE THREAD

**Issue by markusa380** [Netflix/conductor#1356]
I have been trying to get a custom Conductor stack to work.
So far, I have the following compose.yaml:

```yaml
version: '3.7'

services:
  conductor-server:
    environment:
      - CONFIG_PROP=config.properties
    image: conductor2:server
    networks:
      - dragonfly-net
    ports:
      - ${DRAGONFLY_PORT_CONDUCTOR_SERVER}:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/metadata/taskdefs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - elasticsearch
      - dynomite
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  conductor-ui:
    environment:
      - WF_SERVER=http://conductor-server:8080/api/
    image: conductor2:ui
    build:
      context: ../
      dockerfile: docker/ui/Dockerfile
    networks:
      - dragonfly-net
    ports:
      - ${DRAGONFLY_PORT_CONDUCTOR_UI}:5000

  dynomite:
    image: v1r3n/dynomite
    networks:
      - dragonfly-net
    # ports:
    #  - ${DRAGONFLY_PORT_REDIS}:8102
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/8102'
      interval: 5s
      timeout: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  # https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - transport.host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - dragonfly-net
    ports:
    #  - 9200:9200 Port used for HTTP interface
      - ${DRAGONFLY_PORT_ELASTICSEARCH_SERVICE}:9300
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/9300'
      interval: 5s
      timeout: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

# Our overlay network is already defined externally via docker network create command
networks:
  dragonfly-net:
    external: true
    name: ${DRAGONFLY_NETWORK}
```

The Dockerfile for `conductor2:server` looks like this:

```Dockerfile
# --- 0. Clone Conductor repository ---
FROM alpine/git AS git

WORKDIR /usr/src

RUN git clone https://github.com/Netflix/conductor.git

# --- 1. Build ----
FROM gradle:5.6.2-jdk8 AS builder

# Copy the project directly onto the image
COPY --from=git /usr/src/conductor /usr/src/conductor
WORKDIR /usr/src/conductor

# Build the server on run
RUN ./gradlew build -x test

# --- 2. Create binary ---
FROM openjdk:8-jre-alpine

# Make app folders
RUN mkdir -p /app/config /app/logs /app/libs

ADD startup.sh /app/startup.sh
ADD config.properties /app/config/config.properties
ADD log4j.properties /app/config/log4j.properties

# Copy the project directly onto the image
COPY --from=builder /usr/src/conductor/server/build/libs/conductor-server-*-all.jar /app/libs

# Copy the files for the server into the app folders
RUN chmod +x /app/startup.sh

EXPOSE 8080
EXPOSE 8090

CMD [ "/app/startup.sh" ]
ENTRYPOINT [ "/bin/sh"]
```

The config.properties file looks like this:
```
# Servers.
conductor.jetty.server.enabled=true
conductor.grpc.server.enabled=false

# Database persistence model.  Possible values are memory, redis, and dynomite.
# If ommitted, the persistence used is memory
#
# memory : The data is stored in memory and lost when the server dies.  Useful for testing or demo
# redis : non-Dynomite based redis instance
# dynomite : Dynomite cluster.  Use this for HA configuration.

db=dynomite

# Dynomite Cluster details.
# format is host:port:rack separated by semicolon
workflow.dynomite.cluster.hosts=dynomite:8102:none

# Dynomite cluster name
workflow.dynomite.cluster.name=dynomite

# Namespace for the keys stored in Dynomite/Redis
workflow.namespace.prefix=conductor

# Namespace prefix for the dyno queues
workflow.namespace.queue.prefix=conductor_queues

# No. of threads allocated to dyno-queues (optional)
queues.dynomite.threads=10

# Non-quorum port used to connect to local redis.  Used by dyno-queues.
# When using redis directly, set this to the same port as redis server
# For Dynomite, this is 22122 by default or the local redis-server port used by Dynomite.
queues.dynomite.nonQuorum.port=22122

# Elastic search instance type. Possible values are memory and external.
# If not specified, the instance type will be embedded in memory
#
# memory: The instance is created in memory and lost when the server dies. Useful for development and testing.
# external: Elastic search instance runs outside of the server. Data is persisted and does not get lost when
#           the server dies. Useful for more stable environments like staging or production.
workflow.elasticsearch.instanceType=external

# Transport address to elasticsearch
workflow.elasticsearch.url=elasticsearch:9300

# Name of the elasticsearch cluster
workflow.elasticsearch.index.name=conductor

# Additional modules (optional)
# conductor.additional.modules=class_extending_com.google.inject.AbstractModule

# Load sample kitchen sink workflow
loadSample=true
```

The problem manifests in the refusal of any connection attempt to any endpoint (e.g. api/metadata/taskdefs).

The docker log shows this:

```
    for the 2nd parameter of com.netflix.conductor.dyno.RedisQueuesProvider.<init>(RedisQueuesProvider.java:32)

  while locating com.netflix.conductor.dyno.RedisQueuesProvider

  at com.netflix.conductor.dao.RedisWorkflowModule.configure(RedisWorkflowModule.java:33) (via modules: com.google.inject.util.Modules$OverrideModule -> com.netflix.conductor.dao.RedisWorkflowModule)

  while locating com.netflix.dyno.queues.redis.RedisQueues

    for the 1st parameter of com.netflix.conductor.dao.dynomite.queue.DynoQueueDAO.<init>(DynoQueueDAO.java:60)

  at com.netflix.conductor.dao.dynomite.queue.DynoQueueDAO.class(DynoQueueDAO.java:45)

  while locating com.netflix.conductor.dao.dynomite.queue.DynoQueueDAO

  while locating com.netflix.conductor.dao.QueueDAO

    for the 3rd parameter of com.netflix.conductor.core.execution.WorkflowSweeper.<init>(WorkflowSweeper.java:60)

  at com.netflix.conductor.server.ServerModule.configure(ServerModule.java:53) (via modules: com.google.inject.util.Modules$OverrideModule -> com.netflix.conductor.server.ServerModule)

  while locating com.netflix.conductor.core.execution.WorkflowSweeper

Caused by: java.lang.RuntimeException (same stack trace as error #33)

59 errors

at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)

at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)

at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)

at com.google.inject.Guice.createInjector(Guice.java:99)

at com.google.inject.Guice.createInjector(Guice.java:73)

at com.netflix.conductor.bootstrap.Main.main(Main.java:53)
```

The logs produced by the conductor-server application show no problems.

Since I have added the healthcheck to the conductor-server in the compose file the container becomes unhealthy after ~1 minute, as expected if the endpoints are not reachable.

What could be causing this?
