### ISSUE TITLE
An exception occurred: Error polling system task in queue:[START_WORKFLOW|HTTP|JOIN...]

### ISSUE THREAD

**Issue by zengqinglei** [Netflix/conductor#3575]
**Describe the bug**
When I start the conductor through docker-compose -f docker-compose.yaml -f docker-compose-dynomite.yaml up, frequent errors occur: Error polling system task in queue:[START_WORKFLOW|HTTP|JOIN...]
![image](https://user-images.githubusercontent.com/7374317/231372408-6b651cb3-792e-4363-a2e5-168916f35a90.png)
![image](https://user-images.githubusercontent.com/7374317/231372448-44d313bb-a7e1-4950-b0aa-1995fca788d7.png)

**Details**
Conductor version:3.13.5
Persistence implementation: Dynomite
Queue implementation: Dynomite
Lock: NO

**To Reproduce**
1. After pulling git clone {url} to clone the code, use the following command to build the conductor image
``` bash
cd docker/server
docker build -f Dockerfile -t conductor-server:v3.13.5 ../../
cd docker/ui
docker build -f Dockerfile -t conductor-ui:v3.13.5 ../../
```
3. Define docker-compose.yaml
``` yaml
version: '2.3'

services:
  conductor-server:
    environment:
      - TZ=Asia/Shanghai
      - CONFIG_PROP=config-local.properties
    image: conductor:server-v3.13.5
    container_name: conductor-server
    networks:
      - internal
    ports:
      - 8080:8080
    volumes:
      - ./server/config/config-local.properties:/app/config/config-local.properties
      - ./server/config/log4j2.xml:/app/config/log4j2.xml
      - ./server/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl","-I" ,"-XGET", "http://localhost:8080/health"]
      interval: 60s
      timeout: 30s
      retries: 12
    links:
      - elasticsearch:es
      - redis:rs
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "3"

  conductor-ui:
    environment:
      - TZ=Asia/Shanghai
      - WF_SERVER=http://conductor-server:8080
    image: conductor-ui:v3.13.5
    container_name: conductor-ui
    networks:
      - internal
    ports:
      - 5000:5000
    links:
      - conductor-server
    stdin_open: true

  redis:
    image: redis:6.2.3-alpine
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    networks:
      - internal
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]

  elasticsearch:
    image: elasticsearch:6.8.15
    container_name: elasticsearch
    environment:
      - TZ=Asia/Shanghai
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      - transport.host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata-conductor:/usr/share/elasticsearch/data
    networks:
      - internal
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: wget http://localhost:9200/ -O /dev/null
      interval: 5s
      timeout: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "3"

volumes:
  esdata-conductor:
    driver: local

networks:
  internal:
```
4. Define docker-compose-dynomite.yaml
``` yaml
version: '2.3'

services:
  conductor-server:
    environment:
      - TZ=Asia/Shanghai
      - CONFIG_PROP=config.properties
    volumes:
      - ./server/config/config.properties:/app/config/config.properties
      - ./server/config/log4j2.xml:/app/config/log4j2.xml
      - ./server/logs:/app/logs
    links:
      - dynomite:dyno1
    depends_on:
      dynomite:
        condition: service_healthy

  dynomite:
    image: v1r3n/dynomite
    networks:
      - internal
    ports:
      - 8102:8102
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/8102'
      interval: 5s
      timeout: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "3"

networks:
  internal:
```
5. Define config.properties
```
# Servers.
conductor.grpc-server.enabled=false

# Database persistence type.
conductor.db.type=dynomite

# Dynomite Cluster details.
# format is host:port:rack separated by semicolon
conductor.redis.hosts=dyno1:8102:us-east-1c

# Dynomite cluster name
conductor.redis.clusterName=dyno1

# Namespace for the keys stored in Dynomite/Redis
conductor.redis.workflowNamespacePrefix=conductor

# Namespace prefix for the dyno queues
conductor.redis.queueNamespacePrefix=conductor_queues

# No. of threads allocated to dyno-queues (optional)
queues.dynomite.threads=10

# By default with dynomite, we want the repairservice enabled
conductor.app.workflowRepairServiceEnabled=true

# Non-quorum port used to connect to local redis.  Used by dyno-queues.
# When using redis directly, set this to the same port as redis server
# For Dynomite, this is 22122 by default or the local redis-server port used by Dynomite.
conductor.redis.queuesNonQuorumPort=22122

# Elastic search instance indexing is enabled.
conductor.indexing.enabled=true

# Transport address to elasticsearch
conductor.elasticsearch.url=http://es:9200

# Name of the elasticsearch cluster
conductor.elasticsearch.indexName=conductor
#conductor.event-queues.amqp.queueType=classic
#conductor.event-queues.amqp.sequentialMsgProcessing=true

# Additional modules for metrics collection exposed via logger (optional)
# conductor.metrics-logger.enabled=true
# conductor.metrics-logger.reportPeriodSeconds=15

# Additional modules for metrics collection exposed to Prometheus (optional)
# conductor.metrics-prometheus.enabled=true
# management.endpoints.web.exposure.include=prometheus

# To enable Workflow/Task Summary Input/Output JSON Serialization, use the following:
# conductor.app.summary-input-output-json-serialization.enabled=true

# Load sample kitchen sink workflow
loadSample=false

conductor.elasticsearch.clusterHealthColor=yellow

logging.config=/app/config/log4j2.xml
```
6. Define log4j2.xml
``` xml
<Configuration status="WARN">
    <Appenders>
        <Console name="CONSOLE">
            <PatternLayout pattern="%d{ISO8601} %highlight{%-5level }[%style{%t}{bright,blue}] %style{%C{1.}}{bright,yellow}: %msg%n%throwable"/>
        </Console>
    </Appenders>

    <Loggers>
        <Root level="INFO">
            <AppenderRef ref="CONSOLE" />
        </Root>
    </Loggers>
</Configuration>
```
7. Start up：`docker-compose -f docker-compose.yaml -f docker-compose-dynomite.yaml up`
8. See error
![image](https://user-images.githubusercontent.com/7374317/231375817-b5d62661-cdcb-4cce-a67c-36e8b366b71b.png)

But through the UI, I can still add workflows, but not run workflows
![image](https://user-images.githubusercontent.com/7374317/231377508-9a3b383e-5bba-4415-8c77-2f791d4d534a.png)
![image](https://user-images.githubusercontent.com/7374317/231377695-ffa512a1-8bee-4c88-9891-a14c54ff6e0f.png)

When I start conductor via `docker-compose up` , everything works fine.

Looking forward to your reply as soon as possible, thank you!

**Comment by BradenEads** [comment]
It seems like there might be an issue with the Dynomite configuration in your setup. Here are a few suggestions to troubleshoot and potentially fix the problem:

Check Dynomite logs: Inspect the logs of the Dynomite container to see if there are any errors or issues with the configuration. You can view the logs using the following command:

docker logs <dynomite_container_id>

It seems like there might be an issue with the Dynomite configuration in your setup. Here are a few suggestions to troubleshoot and potentially fix the problem:

Check Dynomite logs: Inspect the logs of the Dynomite container to see if there are any errors or issues with the configuration. You can view the logs using the following command:
bash

`docker logs <dynomite_container_id>`

Replace <dynomite_container_id> with the actual container ID of your Dynomite instance.

Verify Dynomite configuration: Make sure that the Dynomite configuration is correct and all required properties are set. You can refer to the [official Dynomite documentation](https://github.com/Netflix/dynomite) for more information on how to configure Dynomite.

Test Dynomite connectivity: Check if Conductor can connect to the Dynomite instance by running a simple command from within the Conductor container:

`docker exec -it <conductor_container_id> redis-cli -h dyno1 -p 8102 ping`

Replace <conductor_container_id> with the actual container ID of your Conductor instance. This command should return PONG if the connection is successful.

Test Dynomite cluster: Make sure that the Dynomite cluster is properly set up and running. If you are using a single-node setup for testing purposes, ensure that the dynomite service in the docker-compose-dynomite.yaml file has the correct configuration.

Inspect Conductor logs: Review the logs of the Conductor container for any error messages or issues related to Dynomite connectivity or configuration. You can view the logs using the following command:

`docker logs <conductor_container_id>`

Replace <conductor_container_id> with the actual container ID of your Conductor instance.

By following these steps, you should be able to identify the root cause of the issue and resolve it. If the issue persists, please provide more information about your setup, any error messages, and logs to help diagnose the problem.

**Comment by zengqinglei** [comment]
@BradenEads I passed docker logs -f dynomite, and stopped the conductor-server, the log content of dynomite is as follows:
![image](https://user-images.githubusercontent.com/7374317/231634515-ed3179a4-ebe5-4d4c-b12c-b88e4e2ad167.png)

I did not find the error from the log, my startup container docker-compose.yaml is as follows, can you help analyze the following:
``` yaml
version: '2.3'

services:
  dynomite:
    environment:
      - TZ=Asia/Shanghai
    container_name: dynomite
    image: v1r3n/dynomite
    networks:
      - internal
    ports:
      - 8102:8102
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/8102'
      interval: 5s
      timeout: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "3"
```
