### ISSUE TITLE
During the running process of the workflow, it terminated unexpectedly, and the task is in the cancel state

### ISSUE THREAD

**Issue by zengqinglei** [Netflix/conductor#3576]
**Describe the bug**
When I run a workflow, the workflow generally has several tasks, sending http requests asynchronously will occasionally and randomly terminate unexpectedly, and the task is in the cancel state

**Details**
Conductor version:3.13.5
Persistence implementation: postgres
Queue implementation: redis
Lock: No
Workflow definition:
``` json
{
  "createTime": 1672215603359,
  "updateTime": 1681284216169,
  "accessPolicy": {},
  "name": "multi_times_request_test",
  "description": "多次请求测试",
  "version": 8,
  "tasks": [
    {
      "name": "等待3秒",
      "taskReferenceName": "wait_data_write",
      "inputParameters": {
        "duration": "3seconds"
      },
      "type": "WAIT",
      "startDelay": 0,
      "optional": false,
      "asyncComplete": false
    },
    {
      "name": "task1",
      "taskReferenceName": "baseOpen",
      "inputParameters": {},
      "type": "FORK_JOIN",
      "forkTasks": [
        [
          {
            "name": "task2",
            "taskReferenceName": "task2",
            "inputParameters": {
              "inputValue": "${workflow.input.APP_AUTHS_MAP}"
            },
            "type": "SWITCH",
            "decisionCases": {
              "open": [
                {
                  "name": "task3",
                  "taskReferenceName": "task3",
                  "inputParameters": {
                    "http_request": {
                      "uri": "https://mock.uutool.cn/test_request",
                      "method": "POST",
                      "connectionTimeOut": 30000,
                      "readTimeOut": 30000,
                      "headers": {
                        "Authorization": "Bearer token"
                      },
                      "body": {
                        "title": "open_ykj",
                        "taskId": "${workflow.workflowId}_openyunkongjian"
                      }
                    }
                  },
                  "type": "HTTP",
                  "startDelay": 0,
                  "optional": false,
                  "asyncComplete": true
                }
              ]
            },
            "startDelay": 0,
            "optional": false,
            "asyncComplete": false,
            "evaluatorType": "javascript",
            "expression": "$.inputValue!=null && $.inputValue.cyykj != null ? 'open' : 'defalut' "
          }
        ]
      ],
      "startDelay": 0,
      "optional": false,
      "asyncComplete": true
    },
    {
      "name": "task4",
      "taskReferenceName": "baseOpenAfter",
      "inputParameters": {},
      "type": "JOIN",
      "startDelay": 0,
      "joinOn": [
        "openyunlianTask",
        "openyunkongjian"
      ],
      "optional": false,
      "asyncComplete": false
    },
    {
      "name": "task5",
      "taskReferenceName": "sendEmail",
      "inputParameters": {
        "http_request": {
          "headers": {
            "Authorization": "Bearer token"
          },
          "connectionTimeOut": 30000,
          "readTimeOut": 30000,
          "uri": "https://mock.uutool.cn/test_request",
          "method": "POST",
          "body": {
            "title": "send_mail",
            "conductorRunId": "${workflow.workflowId}"
          }
        }
      },
      "type": "HTTP",
      "startDelay": 0,
      "optional": true,
      "asyncComplete": false
    }
  ],
  "inputParameters": [],
  "outputParameters": {},
  "schemaVersion": 2,
  "restartable": true,
  "workflowStatusListenerEnabled": false,
  "ownerEmail": "example@email.com",
  "timeoutPolicy": "ALERT_ONLY",
  "timeoutSeconds": 0,
  "variables": {},
  "inputTemplate": {}
}
```

**To Reproduce**
1. After pulling git clone {url} to clone the code, use the following command to build the conductor image
**Add postgres persistent dependency package**
vim server/build.gradle
```
runtimeOnly "org.glassfish.jaxb:jaxb-runtime:${revJAXB}"
runtimeOnly "com.netflix.conductor:conductor-postgres-persistence:3.13.5"
```
**build image**
``` bash
cd docker/server
docker build -f Dockerfile -t conductor-server:v3.13.5 ../../
cd docker/ui
docker build -f Dockerfile -t conductor-ui:v3.13.5 ../../
```
2. Define docker-compose.yaml
``` yaml
version: '2.3'

services:
  conductor-server:
    environment:
      - TZ=Asia/Shanghai
      - CONFIG_PROP=config-local.properties
    image: conductor:server-v3.13.5
    container_name: conductor-server
    networks:
      - internal
    ports:
      - 8080:8080
    volumes:
      - ./server/config/config-local.properties:/app/config/config-local.properties
      - ./server/config/log4j2.xml:/app/config/log4j2.xml
      - ./server/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl","-I" ,"-XGET", "http://localhost:8080/health"]
      interval: 60s
      timeout: 30s
      retries: 12
    links:
      - elasticsearch:es
      - redis:rs
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  conductor-ui:
    environment:
      - TZ=Asia/Shanghai
      - WF_SERVER=http://conductor-server:8080
    image: conductor-ui:v3.13.5
    container_name: conductor-ui
    networks:
      - internal
    ports:
      - 5000:5000
    links:
      - conductor-server
    stdin_open: true

  redis:
    image: redis:6.2.3-alpine
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    networks:
      - internal
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]

  elasticsearch:
    image: elasticsearch:6.8.15
    container_name: elasticsearch
    environment:
      - TZ=Asia/Shanghai
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      - transport.host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata-conductor:/usr/share/elasticsearch/data
    networks:
      - internal
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: wget http://localhost:9200/ -O /dev/null
      interval: 5s
      timeout: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

volumes:
  esdata-conductor:
    driver: local

networks:
  internal:
```
3. Define docker-compose-postgres.yaml
``` yaml
version: '2.3'

services:
  conductor-server:
    environment:
      - TZ=Asia/Shanghai
      - CONFIG_PROP=config-postgres.properties
    image: hub.mingyuanyun.com/tools/conductor:server-v3.13.5
    container_name: conductor-server
    networks:
      - internal
    ports:
      - 8080:8080
    volumes:
      - ./server/config/config-postgres.properties:/app/config/config-postgres.properties
      - ./server/config/log4j2.xml:/app/config/log4j2.xml
      - ./server/logs:/app/logs
    healthcheck:
      test: [ "CMD", "curl","-I" ,"-XGET", "http://localhost:8080/health" ]
      interval: 60s
      timeout: 30s
      retries: 12
    links:
      - elasticsearch:es
      - redis:rs
      - postgres:postgresdb
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "3"

  postgres:
    image: postgres
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_USER=conductor
      - POSTGRES_PASSWORD=conductor
    volumes:
      - pgdata-conductor:/var/lib/postgresql/data
    networks:
      - internal
    ports:
      - 5432:5432
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/5432'
      interval: 5s
      timeout: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"

volumes:
  pgdata-conductor:
    driver: local

networks:
  internal:
```
4. Define config-postgres.properties
```
# Servers.
conductor.grpc-server.enabled=false

# Database persistence type.
conductor.db.type=postgres

spring.datasource.url=jdbc:postgresql://postgres:5432/conductor
spring.datasource.username=conductor
spring.datasource.password=conductor

# Hikari pool sizes are -1 by default and prevent startup
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# Dynomite Cluster details.
# format is host:port:rack separated by semicolon
conductor.redis.hosts=rs:6379:us-east-1c

# Namespace for the keys stored in Dynomite/Redis
conductor.redis.workflowNamespacePrefix=conductor

# Namespace prefix for the dyno queues
conductor.redis.queueNamespacePrefix=conductor_queues

# No. of threads allocated to dyno-queues (optional)
queues.dynomite.threads=10

# By default with dynomite, we want the repairservice enabled
conductor.app.workflowRepairServiceEnabled=true

# Non-quorum port used to connect to local redis.  Used by dyno-queues.
# When using redis directly, set this to the same port as redis server
# For Dynomite, this is 22122 by default or the local redis-server port used by Dynomite.
conductor.redis.queuesNonQuorumPort=22122

# Elastic search instance indexing is enabled.
conductor.indexing.enabled=true

# Transport address to elasticsearch
conductor.elasticsearch.url=http://es:9200
conductor.elasticsearch.indexReplicasCount=0

# Name of the elasticsearch cluster
conductor.elasticsearch.indexName=conductor

# Load sample kitchen sink workflow
loadSample=false

conductor.elasticsearch.clusterHealthColor=yellow

logging.config=/app/config/log4j2.xml
logging.log4j2.config.override=/app/config/log4j2.xml
```
5. Define log4j2.xml
``` xml
<Configuration status="WARN">
    <Appenders>
        <Console name="CONSOLE">
            <PatternLayout pattern="%d{ISO8601} %highlight{%-5level }[%style{%t}{bright,blue}] %style{%C{1.}}{bright,yellow}: %msg%n%throwable"/>
        </Console>
    </Appenders>

    <Loggers>
        <Root level="INFO">
            <AppenderRef ref="CONSOLE" />
        </Root>
    </Loggers>
</Configuration>
```
6. Start up：`docker-compose -f docker-compose.yaml -f docker-compose-postgres.yaml up`
7. Visit http://localhost:5000 to create a workflow
``` json
{
  "createTime": 1672215603359,
  "updateTime": 1681284216169,
  "accessPolicy": {},
  "name": "multi_times_request_test",
  "description": "多次请求测试",
  "version": 8,
  "tasks": [
    {
      "name": "等待3秒",
      "taskReferenceName": "wait_data_write",
      "inputParameters": {
        "duration": "3seconds"
      },
      "type": "WAIT",
      "startDelay": 0,
      "optional": false,
      "asyncComplete": false
    },
    {
      "name": "task1",
      "taskReferenceName": "baseOpen",
      "inputParameters": {},
      "type": "FORK_JOIN",
      "forkTasks": [
        [
          {
            "name": "task2",
            "taskReferenceName": "task2",
            "inputParameters": {
              "inputValue": "${workflow.input.APP_AUTHS_MAP}"
            },
            "type": "SWITCH",
            "decisionCases": {
              "open": [
                {
                  "name": "task3",
                  "taskReferenceName": "task3",
                  "inputParameters": {
                    "http_request": {
                      "uri": "https://mock.uutool.cn/test_request",
                      "method": "POST",
                      "connectionTimeOut": 30000,
                      "readTimeOut": 30000,
                      "headers": {
                        "Authorization": "Bearer token"
                      },
                      "body": {
                        "title": "open_ykj",
                        "taskId": "${workflow.workflowId}_openyunkongjian"
                      }
                    }
                  },
                  "type": "HTTP",
                  "startDelay": 0,
                  "optional": false,
                  "asyncComplete": true
                }
              ]
            },
            "startDelay": 0,
            "optional": false,
            "asyncComplete": false,
            "evaluatorType": "javascript",
            "expression": "$.inputValue!=null && $.inputValue.cyykj != null ? 'open' : 'defalut' "
          }
        ]
      ],
      "startDelay": 0,
      "optional": false,
      "asyncComplete": true
    },
    {
      "name": "task4",
      "taskReferenceName": "baseOpenAfter",
      "inputParameters": {},
      "type": "JOIN",
      "startDelay": 0,
      "joinOn": [
        "openyunlianTask",
        "openyunkongjian"
      ],
      "optional": false,
      "asyncComplete": false
    },
    {
      "name": "task5",
      "taskReferenceName": "sendEmail",
      "inputParameters": {
        "http_request": {
          "headers": {
            "Authorization": "Bearer token"
          },
          "connectionTimeOut": 30000,
          "readTimeOut": 30000,
          "uri": "https://mock.uutool.cn/test_request",
          "method": "POST",
          "body": {
            "title": "send_mail",
            "conductorRunId": "${workflow.workflowId}"
          }
        }
      },
      "type": "HTTP",
      "startDelay": 0,
      "optional": true,
      "asyncComplete": false
    }
  ],
  "inputParameters": [],
  "outputParameters": {},
  "schemaVersion": 2,
  "restartable": true,
  "workflowStatusListenerEnabled": false,
  "ownerEmail": "example@email.com",
  "timeoutPolicy": "ALERT_ONLY",
  "timeoutSeconds": 0,
  "variables": {},
  "inputTemplate": {}
}
```
8. Run this workflow multiple times
``` json
{
  "APP_AUTHS_MAP": {
    "cyyl": [],
    "cyykj": []
  }
}
```
![image](https://user-images.githubusercontent.com/7374317/231386481-bf938ecb-1c2a-4594-b6a0-423331bc72f4.png)
9. It may happen randomly next that the process is terminated and the task is in a canceled state
![image](https://user-images.githubusercontent.com/7374317/231386907-8fcf556e-209a-4da9-b258-94e65bdec5b5.png)
Through the log, you can see that there is a log as follows：
![image](https://user-images.githubusercontent.com/7374317/231387381-16e39ea3-7c5c-42e8-87ef-16e520d437cd.png)

**This problem has appeared frequently and randomly in our production environment, causing serious business flow problems. I hope your team can help us analyze the possible causes and provide some solutions as soon as possible. Thank you very much!**
